### ISSUE TITLE
Subgraph fails to load with "id not found"

### ISSUE THREAD

**Issue by Manik-Jain** [graphprotocol/graph-network-subgraph#115]
Hello,

I've created and deployed a new test Sub-graph. 
The deployment was a success from CLI.

However, it fails to load content on the dashboard under : https://thegraph.com/explorer/subgraph/manik-jain/Manik

In the developer console, I get id not found error. 
Attaching the screenshot for the same.
<img width="1435" alt="Screenshot 2021-05-04 at 17 07 02" src="https://user-images.githubusercontent.com/24981979/117070038-3c196c80-acfb-11eb-8590-bbf71fb4d0e3.png">

**Comment by katopz** [comment]
try https://thegraph.com/explorer/subgraph/manik-jain/manik

**Comment by juanmardefago** [comment]
I think this must've happened during some outage, since it seems to work just fine.

Anyways, it's more UI related than related to the network subgraph from the looks of it
