### ISSUE TITLE
Add closedAt to Allocation entity

### ISSUE THREAD

**Issue by abarmat** [graphprotocol/graph-network-subgraph#124]
It would be great to have a `closedAt` in the Allocation entity. It can help with some analytics.

**Comment by abarmat** [comment]
I see it is related to https://github.com/graphprotocol/graph-network-subgraph/issues/86

**Comment by davekaj** [comment]
Allocation has:

```
  "Epoch this allocation was created"
  createdAtEpoch: Int!
  "Block at which this allocation was created"
  createdAtBlockHash: Bytes!
  "Epoch this allocation was closed in"
  closedAtEpoch: Int!
  "Block hash at which this allocation was closed"
  closedAtBlockHash: Bytes
  ```
  
  Are you requesting for `closedAtBlock`? If so , maybe @juanmardefago can add it into the next pr, it would be a quick fix. 

we then may as well add `createdAtBlock` to it as well

**Comment by abarmat** [comment]
The Allocation entity has a:
```
createdAt Int!
Timestamp this allocation was created at
```

I'm proposing to do something like
```
closedAt Int!
Timestamp this allocation was closed at
```

**Comment by juanmardefago** [comment]
@abarmat yeah, no worries, we can add those!

**Comment by juanmardefago** [comment]
@abarmat I just double checked, and it's already implemented on the `mainnet-staging` branch.
It was added in PR #111
