### ISSUE TITLE
feature request: allocationCount in GraphNetwork entity

### ISSUE THREAD

**Issue by sahra-karakoc** [graphprotocol/graph-network-subgraph#259]
Currently, network subgraph doesn't track network-wide `allocationCount`. It would be useful to add it to the `GraphNetwork` entity. 

Similar fields exist for the `Indexer` entity:

> "Number of active allocations of stake for this Indexer"
  allocationCount: Int!
  "All allocations for this Indexer (i.e. closed and active)"
  totalAllocationCount: BigInt!

**Comment by juanmardefago** [comment]
PR for this: https://github.com/graphprotocol/graph-network-subgraph/pull/262

Changed the name slightly to make it more in line to what the `GraphNetwork` entity normally uses.

Will be merged to mainnet staging as soon as the dev-subgraph is confirmed working

**Comment by juanmardefago** [comment]
This has been merged and it's gonna be released in production endpoints tomorrow!
