### ISSUE TITLE
Add trigger to deploy subgraph to a hosted service end point when the merge is based on that branch

### ISSUE THREAD

**Issue by davekaj** [graphprotocol/graph-network-subgraph#66]
Suggested by Ford. We should do it ASAP, it will make the dev environment a bit cleaner.

**Comment by juanmardefago** [comment]
Updating this to avoid having already solved issues. Currently the github workflows deploy to hosted service on specific merges (mainnet-staging pushes testnet and staging deployments, tag to master pushes deployment on the graph-network-mainnet subgraph)
