### ISSUE TITLE
Indexing Rewards misattributed to Delegator Pool when the pool is empty

### ISSUE THREAD

**Issue by madumas** [graphprotocol/graph-network-subgraph#71]
In Staking smart contract, if pool.tokens=0, no indexing rewards are distributed to delegators, which is ok, because there are no delegators.

```    
function _collectDelegationIndexingRewards(address _indexer, uint256 _tokens)
        private
        returns (uint256)
    {
        uint256 delegationRewards = 0;
        DelegationPool storage pool = delegationPools[_indexer];
        if (pool.tokens > 0 && pool.indexingRewardCut < MAX_PPM) {
            uint256 indexerCut = uint256(pool.indexingRewardCut).mul(_tokens).div(MAX_PPM);
            delegationRewards = _tokens.sub(indexerCut);
            pool.tokens = pool.tokens.add(delegationRewards);
        }
        return delegationRewards;
    }
```

When the subgraph processes the resulting RewardsAssigned event, the rewards are attributed to the non-existing delegators.
https://github.com/graphprotocol/graph-network-subgraph/blob/master/src/mappings/rewardsManager.ts#L22

This results in inflating the `delegationExchangeRate` (not immediately, but as soon as one delegator joins) for all the future delegation. This will make the subgraph return a larger delegator balance than what would be determined when looking directly at the smart contract.

**Comment by davekaj** [comment]
Wow great catch! This is for sure a bug. We will fix it in the next few days.
