### ISSUE TITLE
The current epoch just keeps on loading

### ISSUE THREAD

**Issue by aditya-manit** [graphprotocol/graph-network-subgraph#85]
Not related to the contract itself but related to the UI part maybe.
![https_network thegraph com_epochs_02_38_33](https://user-images.githubusercontent.com/40714633/104856116-bda8e280-5936-11eb-9688-158001535011.png)

**Comment by juanmardefago** [comment]
This has been fixed for a while, but as mentioned, it was actually an UI bug :)
