### ISSUE TITLE
Sorting and filtering epochs by ID does not work as expected.

### ISSUE THREAD

**Issue by Ryabina-io** [graphprotocol/graph-network-subgraph#90]
Epoches id is ID type i.e. String. Therefore, such a query 
```
{
   epoches(orderBy:id orderDirection:asc where:{id_gte:"20", id_lte:"30"}){
     id
   }
}
```
would use string filtering and sorting, but it is more convenient to use numeric.

Is it possible to add an additional duplicate ID field but in Int format?

**Comment by davekaj** [comment]
Hey! I understand the problem, it does not sort well like this. It would be a good improvement to `graph-node` but we haven't implemented it as it's not a super high priority. Usually, there are work arounds. For example, you can query:

````
{
   epoches(orderBy:startBlock orderDirection:desc){
     id
   }
}
```

This will return it in order. Will this solve your problem?

**Comment by Ryabina-io** [comment]
Yes, it solves the sorting problem. For filtering, I can check first startBlock in epoch 20 and then in epoch 30 and create a query

```
{
    epoches(where:{startBlock_gte:11579688 startBlock_lte:11646148}){
        id
        startBlock
    }
}
```
So, yes issue seems solved.
